[project]
name = 'Community-Owned'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Community-Owned]
path = 'contracts/Community-Owned.clar'
clarity_version = 3
epoch = 3.1

[contracts.grid-performance]
path = 'contracts/grid-performance.clar'
clarity_version = 3
epoch = 3.1

[contracts.grid-maintenance]
path = 'contracts/grid-maintenance.clar'
clarity_version = 3
epoch = 3.1

[contracts.grid-insurance]
path = 'contracts/grid-insurance.clar'
clarity_version = 3
epoch = 3.1

[contracts.grid-governance]
path = 'contracts/grid-governance.clar'
clarity_version = 3
epoch = 3.1

[contracts.grid-carbon-credits]
path = 'contracts/grid-carbon-credits.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
